### ISSUE TITLE
vertex color node not behaving as expected + errors

### ISSUE THREAD

**Issue by trobins78** [cocos/cocos-creator-extensions#14]
-basic unlit shader example using vertex color node (no error but I would expect to see the vertex colors defined by the model)
![image](https://github.com/cocos/cocos-creator-extensions/assets/96149949/c7cb18fb-dcd0-460b-abf8-b979f90f9621)

Input model from Maya:
![image](https://github.com/cocos/cocos-creator-extensions/assets/96149949/f0becb96-0341-42b1-9898-b67dc37e6dd8)
Output in Cocos (with above graph):
![image](https://github.com/cocos/cocos-creator-extensions/assets/96149949/66ad5725-8757-4836-8d10-a097a1221d87)

Surface shader example:
![image](https://github.com/cocos/cocos-creator-extensions/assets/96149949/46333725-3259-4e6c-9d3f-cec42a596dff)
Same model as used above with vert col passed to albedo:
![image](https://github.com/cocos/cocos-creator-extensions/assets/96149949/634f6ac8-bd84-40b2-a1b9-65d3b42def36)
Same but passed to emission:
![image](https://github.com/cocos/cocos-creator-extensions/assets/96149949/b383fe30-deec-42d6-8142-83308df476b9)

Further, if I attempt something such as:
![image](https://github.com/cocos/cocos-creator-extensions/assets/96149949/396b4052-5d39-4856-b803-5a00f8c0ab7e)

I get the following error:
[Assets] Cannot read property 'dependencies' of null
TypeError: Cannot read property 'dependencies' of null
at D:\Work_Related\GITHUB_REPOS\playspace\extensions\shader-graph\src\importer\utils-3.8.ts:40:37
at C:\ProgramData\cocos\editors\Creator\3.8.2\resources\app.asar\node_modules\@editor\source\index.ts:21:9
at Array.forEach (<anonymous>)
at forEach (C:\ProgramData\cocos\editors\Creator\3.8.2\resources\app.asar\node_modules\@editor\source\index.ts:20:22)
at generateEffectAsset (D:\Work_Related\GITHUB_REPOS\playspace\extensions\shader-graph\src\importer\utils-3.8.ts:39:5)
at ShaderGraph380.import (D:\Work_Related\GITHUB_REPOS\playspace\extensions\shader-graph\src\importer\shader-graph-3.8.ts:38:13)

**Comment by trobins78** [comment]
Please let me know if there are ways that I can work around these issues as the editor matures. Thank you!
